### PR TITLE
Easier workflow and lil' features

### PR DESCRIPTION
**Pull request by xChillax**
-Added support for assigning player1, player2 and chart speed within the simfile properties.
-Converted files now export in lowercase and with a dash instead of spaces (no need to keep renaming the file anymore).
-Simplified the messages when it starts converting a file.
-Added messages to tell whenever it's done converting a file.
-Changed required difficulty from Challenge to Hard, and files now convert to simfile with the difficulty set to Hard, instead of Medium. For consistency and easier workflow.
-Default value for "needsVoices" is now set to "True", since FNF songs normally use voices, in most scenarios.
-Added .exe for accessibility.

### CODE REVIEW

**Comment by arceuss** [comment]
itd be nice to export each difficulty tho so i dont have to keep editing the script

**Comment by xChillax** [comment]
I was considering adding that, I will do it if I have time.

**Comment by Kade-github** [comment]
I already did a lot of these without looking at this I'm sorry :(

**Comment by xChillax** [comment]
Oh, it's okey. I felt I should have messaged you personally when I had it done (which was before I even posted this here), but that's cool notheless!

**Comment by xChillax** [comment]
Feel free to close it! and if there is anything else that's missing on your new version I can just do a new pull request/edit this one. :)

**Comment by xChillax** [comment]
I didn't got time to implement the difficulty exporting, but I had some time to fix up the pull to include the things from the latest commit and did some tiny changes too.

-Stage can now be defined via the "Background" property within the Simfile.
-Now properly sets difficulty depending on the name of the chart, meaning that if your chart has "-hard", it will automaticly be set to the Hard difficulty within the Simfile, instead of always being set to "Medium". Works for other difficulties too.
-"stage" no longer gets printed into the .json file if it's missing from the file (ie: not defined on the Simfile neither input manually when converting).
-You will only be prompted to input data if it cannot be found within the Simfile.

Let me know if there is anything wrong or if it needs any changes. I was in a bit of a rush.

Also heads up, but I just noticed that the .exe is suddenly throwing a false virus warning since, Windows Defender loves to check for "non signed files" and if your .exe is or isn't "trusted" (aka has enough reputation). I could try to look for a fix, self signing the file might help but, honestly this has been a pain to figure out.

**Comment by arceuss** [comment]
@KadeDev theres no issues on here but when will bpm changes be supported since theyre in kade engine now

**Pull request closed without merging**
